export const INIT_PAYMENTS_REQUEST = "INIT_PAYMENTS_REQUEST";
export const INIT_PAYMENTS_SUCCESS = "INIT_PAYMENTS_SUCCESS";
export const INIT_PAYMENTS_FAIL = "INIT_PAYMENTS_FAIL";

export const EXECUTE_REQUEST_JSON = "EXECUTE_REQUEST_JSON";
